name: Build and Push Add-on

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Add-on
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      
    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ”‘ Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: âš™ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ”¨ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ—ï¸ Build and Push Add-on Image
        uses: docker/build-push-action@v5
        with:
          context: ./copyparty
          file: ./copyparty/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/simeleo20/copyparty-ha-addon:latest
            ghcr.io/simeleo20/copyparty-ha-addon:${{ github.ref_name }}

      - name: âœ… Update Home Assistant Add-on Config
        uses: "home-assistant/builder@master"
        with:
          args: |
            --target ghcr.io/simeleo20/copyparty-ha-addon
            --target_config ${{ github.workspace }}/copyparty/config.json 
            --target_repo https://github.com/${{ github.repository }}
            --target_tag ${{ github.ref_name }}