name: Build and Push Add-on

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Add-on
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      
    steps:
      - name: ‚¨áÔ∏è Checkout Repository
        uses: actions/checkout@v4

      - name: üîë Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ‚öôÔ∏è Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: üî® Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üèóÔ∏è Build and Push Add-on Image
        uses: docker/build-push-action@v5
        with:
          context: ./copyparty
          file: ./copyparty/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/simeleo20/copyparty-ha-addon:latest
            ghcr.io/simeleo20/copyparty-ha-addon:${{ github.ref_name }}

      - name: üåê Create Multi-Architecture Manifest
        id: create_manifest
        run: |
          # Definisce il nome base dell'immagine
          IMAGE_NAME="ghcr.io/simeleo20/copyparty-ha-addon"
          
          # Definisce i tag da raggruppare
          TAGS="${IMAGE_NAME}:latest ${IMAGE_NAME}:${{ github.ref_name }}"
          
          # Definisce le immagini specifiche per architettura caricate prima
          IMAGES_TO_GROUP="\
          ${IMAGE_NAME}:latest-amd64 \
          ${IMAGE_NAME}:latest-armv7 \
          ${IMAGE_NAME}:latest-arm64"
          
          # 1. Crea e annota il manifest list (richiede BuildX)
          docker manifest create ${TAGS} ${IMAGES_TO_GROUP}
          
          # 2. Spinge il manifest list sul GHCR
          docker manifest push ${TAGS}
        shell: bash